### ISSUE TITLE
Parse name from email

### ISSUE THREAD

**Issue by miiila** [ralyodio/humanparser#13]
Do you consider valuable and meaningful feature for parsing name out of an email address? E.g. mila.votradovec@gmail.com => Mila Votradovec.

I am willing to contribute, but want to discuss the idea first.

**Comment by chovy** [comment]
Yes, I think that's a great idea. You could just split on `.` and then join on space. delimiter and then run the same name matching function on the string.

`var emailFullName = email.split('.').join(' ');`

I'm happy to have this addition.

**Comment by miiila** [comment]
@chovy I realised this is still here after 2 years :-D I'll try to submit a PR by the end of this week.

**Comment by chovy** [comment]
Sounds good!
