### ISSUE TITLE
Support for Name + Address

### ISSUE THREAD

**Issue by Logic-Bits** [ralyodio/humanparser#38]
Hi!

Thanks for everything you did so far!
I think it would be great if someone can just copy and paste name + address (eg. Clipboard).
Right now it doesn't work and you need to copy paste twice or do some extra separation work outside the plugin.

Thanks!

**Comment by ralyodio** [comment]
i don't follow what you're suggesting

**Comment by Logic-Bits** [comment]
Hi.

That was some while ago.
But i think to be able to copy name + address (eg from a website) that it can be parsed completely.

Name family name 
Street
Zip code / county
Country 

Know what I mean?

**Comment by ralyodio** [comment]
this is a library you can pass it the data however you want.
