### ISSUE TITLE
Requirements Status link is broken?

### ISSUE THREAD

**Issue by Tamir198** [ralyodio/humanparser#55]
Hey, when clicking this link: 

![image](https://github.com/ralyodio/humanparser/assets/34707669/11b4993f-0dac-4f83-be92-dcd7b23253cf)

It seems to be broken: 

![image](https://github.com/ralyodio/humanparser/assets/34707669/d1e4806c-0fba-41df-a0c1-2d9b95e8632d)

**Comment by ralyodio** [comment]
fixing now.

**Comment by ralyodio** [comment]
Looks like travis-ci now requires a credit card. I'll remove it.
